-- AlterTable
ALTER TABLE "MatchStats" ADD COLUMN     "medalAccuracy" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "medalAssists" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "medalCaptures" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "medalCombokill" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "medalDefends" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "medalExcellent" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "medalFirstfrag" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "medalHeadshot" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "medalHumiliation" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "medalImpressive" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "medalMidair" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "medalPerfect" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "medalPerforated" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "medalQuadgod" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "medalRampage" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "medalRevenge" INTEGER NOT NULL DEFAULT 0;

-- CreateIndex
CREATE INDEX "MatchStats_map_idx" ON "MatchStats"("map");
